### ISSUE TITLE
Permission issue on docker - QNAP Container Station

### ISSUE THREAD

**Issue by Estarna** [borgbase/vorta-docker#15]
Hi there,

Installed the container pulled from docker "pull ghcr.io/borgbase/vorta-docker:383cccc"

Running and accessing the GUI fine. However when trying to add a new repository, I have this message saying that I have a permission issue. Any clue/help would be appreciated.

Regards,

-Eric

*****

ERROR - Traceback (most recent call last):
[app         ]   File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5168, in main
[app         ]     exit_code = archiver.run(args)
[app         ]   File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 5099, in run
[app         ]     return set_ec(func(args))
[app         ]   File "/usr/lib/python3.10/site-packages/borg/archiver.py", line 168, in wrapper
[app         ]     with repository:
[app         ]   File "/usr/lib/python3.10/site-packages/borg/repository.py", line 198, in __enter__
[app         ]     self.create(self.path)
[app         ]   File "/usr/lib/python3.10/site-packages/borg/repository.py", line 282, in create
[app         ]     with open(os.path.join(path, 'README'), 'w') as fd:
[app         ] PermissionError: [Errno 13] Permission denied: '/share/CACHEDEV2_DATA/Backup Space/Clients-Sauvegardes-Borg/README'
[app         ] Platform: Linux 69950c495c6a 5.10.60-qnap #1 SMP Thu Jan 12 07:27:50 CST 2023 x86_64
[app         ] Linux: Unknown Linux  
[app         ] Borg: 1.2.3  Python: CPython 3.10.9 msgpack: 1.0.4 fuse: pyfuse3 3.2.2 [pyfuse3,llfuse]
[app         ] PID: 592  CWD: /etc/services.d/app
[app         ] sys.argv: ['/usr/bin/borg', 'init', '--info', '--log-json', '--encryption=repokey-blake2', '/share/CACHEDEV2_DATA/Backup Space/Clients-Sauvegardes-Borg']
[app         ] SSH_ORIGINAL_COMMAND: None
[app         ] 2023-02-21 14:21:49,374 - vorta.borg.jobs_manager - DEBUG - Finish job for site: default
[app         ] 2023-02-21 14:21:49,375 - vorta.borg.jobs_manager - DEBUG - No more jobs for site: defaul

**Comment by Estarna** [comment]
OK Thanks anyway
